[project]
name = "samples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datafusion>=43.1.0",
    "duckdb>=1.1.3",
    "faker>=33.3.0",
    "pyarrow>=18.1.0",
]
